from .config_controller import ConfigController
from .main_controller import MainWindowController
from .scratch_pad_controller import ScratchPadController
from .shortcut_controller import ShortcutController
from .toolbar_controller import ToolbarController
